const ADD_TODO = "ADD_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";

const ADD_GOAL = "ADD_GOAL";
const REMOVE_GOAL = "REMOVE_GOAL";

module.exports = {
  ADD_GOAL,
  REMOVE_GOAL,
  ADD_TODO,
  REMOVE_TODO,
  TOGGLE_TODO,
};
